name: Generate QM Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'translations/*.ts'
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 02:00 UTC

jobs:
  generate-qm:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Qt Tools
        run: |
          sudo apt update
          sudo apt install -y qt6-l10n-tools

      - name: Generate .qm files
        run: |
          mkdir -p qm
          LRELEASE_PATH=$(find /usr -name lrelease -type f 2>/dev/null | head -n 1)
          if [ -z "$LRELEASE_PATH" ]; then
            echo "Error: lrelease not found!"
            exit 1
          else
            echo "lrelease found at: $LRELEASE_PATH"
            for ts_file in translations/*.ts; do
              qm_file="qm/$(basename "$ts_file" .ts).qm"
              "$LRELEASE_PATH" "$ts_file" -nounfinished -removeidentical -qm "$qm_file"
            done
          fi

      - name: Package .qm files
        run: |
          (cd qm && zip -r ../RPCS3-languages.zip .)

      - name: Upload Translations as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPCS3-languages
          path: RPCS3-languages.zip